import {
  Search,
  Settings,
  X,
  Lock,
  RefreshCw,
  QrCode,
  MapPin,
  ShoppingBag,
  Package,
  ChevronRight,
  ChevronDown,
  Check,
  AlertTriangle,
  CircleCheck,
  Inbox,
  Trash2,
  Plus,
  Minus,
  LogOut,
  LogIn,
  User,
  Clock,
  Wifi,
  WifiOff,
  ExternalLink,
  Edit3,
  Eye,
  EyeOff,
  type LucideIcon,
} from 'lucide-react';

export const ICONS = {
  search: Search,
  settings: Settings,
  close: X,
  lock: Lock,
  refresh: RefreshCw,
  qrCode: QrCode,
  location: MapPin,
  bag: ShoppingBag,
  package: Package,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  check: Check,
  warning: AlertTriangle,
  success: CircleCheck,
  empty: Inbox,
  delete: Trash2,
  plus: Plus,
  minus: Minus,
  logout: LogOut,
  login: LogIn,
  user: User,
  clock: Clock,
  online: Wifi,
  offline: WifiOff,
  externalLink: ExternalLink,
  edit: Edit3,
  show: Eye,
  hide: EyeOff,
} as const satisfies Record<string, LucideIcon>;

export type IconKey = keyof typeof ICONS;
